// Code generated by hertz generator.

package user

import (
	jwt "Ephyra-genesis-api/biz/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usergetuserprofileMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{jwt.JwtMiddleware.MiddlewareFunc()}
}

func _usergetuserrankingMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{jwt.JwtMiddleware.MiddlewareFunc()}
}

func _usersetuserprofileMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{jwt.JwtMiddleware.MiddlewareFunc()}
}

func _get_user_profileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_user_rankingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _set_user_profileMw() []app.HandlerFunc {
	// your code...
	return nil
}
