// Code generated by hertz generator.

package task

import (
	jwt "Ephyra-genesis-api/biz/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _can_submit_answerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskcansubmitanswerMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{jwt.JwtMiddleware.MiddlewareFunc()}
}

func _daily_questionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskgetdailyquestionsMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{jwt.JwtMiddleware.MiddlewareFunc()}
}

func _get_answer_tx_statusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskgetanswertxstatusMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{jwt.JwtMiddleware.MiddlewareFunc()}
}
