// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBadge = "badge"

// Badge mapped from table <badge>
type Badge struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:badge id" json:"id"`        // badge id
	Name             string    `gorm:"column:name;not null;comment:徽章名称" json:"name"`                             // 徽章名称
	ImageURL         string    `gorm:"column:image_url;not null;comment:徽章图片链接" json:"image_url"`                 // 徽章图片链接
	UnlockConditions string    `gorm:"column:unlock_conditions;not null;comment:徽章解锁条件" json:"unlock_conditions"` // 徽章解锁条件
	UpdateAt         time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                            // 更新时间
	CreateAt         time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"`  // 创建时间
}

// TableName Badge's table name
func (*Badge) TableName() string {
	return TableNameBadge
}
