// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQuestion = "questions"

// Question mapped from table <questions>
type Question struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                        // 主键ID
	Title    string    `gorm:"column:title;not null;comment:问题标题" json:"title"`                                       // 问题标题
	Content  string    `gorm:"column:content;not null;comment:问题详细内容" json:"content"`                                 // 问题详细内容
	Type     int32     `gorm:"column:type;not null;default:1;comment:问题类型：1-单选题，2-多选题，3-填空题，4-问答题，5-判断题" json:"type"` // 问题类型：1-单选题，2-多选题，3-填空题，4-问答题，5-判断题
	UpdateAt time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                                        // 更新时间
	CreateAt time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"`              // 创建时间
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
