// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserPointsLog = "user_points_log"

// UserPointsLog mapped from table <user_points_log>
type UserPointsLog struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户积分变化日志唯一ID" json:"id"`   // 用户积分变化日志唯一ID
	UserID      int64     `gorm:"column:user_id;not null;comment:用户唯一ID" json:"user_id"`                    // 用户唯一ID
	TotalPoints int32     `gorm:"column:total_points;not null;comment:积分变化" json:"total_points"`            // 积分变化
	BasePoints  int32     `gorm:"column:base_points;not null;comment:积分变化" json:"base_points"`              // 积分变化
	ExtraPoints int32     `gorm:"column:extra_points;not null;comment:积分变化" json:"extra_points"`            // 积分变化
	Type        string    `gorm:"column:type;not null;comment:积分类型" json:"type"`                            // 积分类型
	UpdateAt    time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                           // 更新时间
	CreateAt    time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
}

// TableName UserPointsLog's table name
func (*UserPointsLog) TableName() string {
	return TableNameUserPointsLog
}
