// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		Badge:            newBadge(db, opts...),
		Question:         newQuestion(db, opts...),
		User:             newUser(db, opts...),
		UserDailyTaskLog: newUserDailyTaskLog(db, opts...),
		UserPointsLog:    newUserPointsLog(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Badge            badge
	Question         question
	User             user
	UserDailyTaskLog userDailyTaskLog
	UserPointsLog    userPointsLog
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Badge:            q.Badge.clone(db),
		Question:         q.Question.clone(db),
		User:             q.User.clone(db),
		UserDailyTaskLog: q.UserDailyTaskLog.clone(db),
		UserPointsLog:    q.UserPointsLog.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Badge:            q.Badge.replaceDB(db),
		Question:         q.Question.replaceDB(db),
		User:             q.User.replaceDB(db),
		UserDailyTaskLog: q.UserDailyTaskLog.replaceDB(db),
		UserPointsLog:    q.UserPointsLog.replaceDB(db),
	}
}

type queryCtx struct {
	Badge            *badgeDo
	Question         *questionDo
	User             *userDo
	UserDailyTaskLog *userDailyTaskLogDo
	UserPointsLog    *userPointsLogDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Badge:            q.Badge.WithContext(ctx),
		Question:         q.Question.WithContext(ctx),
		User:             q.User.WithContext(ctx),
		UserDailyTaskLog: q.UserDailyTaskLog.WithContext(ctx),
		UserPointsLog:    q.UserPointsLog.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
