// Code generated by hertz generator.

package common

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _contributionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commoncontributionsMw() []app.HandlerFunc {
	// your code...
	return nil
}
