// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	common "Ephyra-genesis-api/biz/router/common"
	login "Ephyra-genesis-api/biz/router/login"
	task "Ephyra-genesis-api/biz/router/task"
	user "Ephyra-genesis-api/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	common.Register(r)

	user.Register(r)

	task.Register(r)

	login.Register(r)
}
