name: Build and Push Image
on: [ push ]

jobs:
  build:
    name: Build and push image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ephyra
          password: ephyra1122

      - name: Set image tag
        id: set-image-tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "tag=latest-${{ github.sha }}" >> $GITHUB_ENV
          else
          BRANCH_NAME=${{ github.ref_name }}
          echo "tag=${BRANCH_NAME}-${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ephyra/ephyra-genesis-api:${{ env.tag }}

      - name: Print image url
        run: echo "Image pushed to docker.io/ephyra/ephyra-genesis-api:${{ env.tag }}"